  version: '3'
  services:
    node-app:
      build: .
      ports:
        - "3000:3000"
      depends_on:
        - mongo
        - redis
      environment:
      - PORT=3000

    mongo:
      image: "mongo:latest"
      ports:
        - "27018:27017"
      depends_on:
      - redis
      environment:
        - DB_URL=mongodb://mongo:27017/redis
      volumes:
        - mongo-data:/data/db

    redis:
      image: "redis:latest"
      ports:
        - "6379:6379"
      environment:
        - REDIS_HOST=redis
        - REDIS_PORT=6379
        - REDIS_USERNAME=Montaser Hassan
        - REDIS_PASSWORD=Mont@ser19

  volumes:
    mongo-data: